version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env

  postgres:
    image: postgres:14-alpine
    container_name: postgresql
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - /var/lib/postgresql/data

  auth:
    container_name: auth-service
    build:
      context: ./
      dockerfile: ./apps/auth/Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq
    command: npm run start:dev auth

  api:
    container_name: api
    build:
      context: ./
      dockerfile: ./apps/api/Dockerfile
    ports:
      - '4000:4000'
    env_file:
      - .env
    command: npm run start:dev api

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - auth
      - api
