version: '3'

networks:
  microservice_network:

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env
    networks:
      - microservice_network

  postgres:
    image: postgres:14-alpine
    container_name: postgresql
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - /var/lib/postgresql/data
    networks:
      - microservice_network

  auth:
    container_name: auth-service
    build:
      context: ./
      dockerfile: ./apps/auth/Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - microservice_network

  api:
    container_name: api
    build:
      context: ./
      dockerfile: ./apps/api/Dockerfile
    env_file:
      - .env
    networks:
      - microservice_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    networks:
      - microservice_network
